# Generated by Django 5.2.12 on 2026-03-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('porcentaje', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FirmaEtica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firma_imagen', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('aceptado', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documento')),
            ],
        ),
    ]
