# Generated by Django 5.2.12 on 2026-03-14 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('induccion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmaetica',
            name='trabajador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma_etica', to='personal.trabajador'),
        ),
        migrations.AddField(
            model_name='lecturadocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='documentos.documento'),
        ),
        migrations.AddField(
            model_name='lecturadocumento',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='personal.trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturadocumento',
            unique_together={('trabajador', 'documento')},
        ),
    ]
