# Generated by Django 5.2.12 on 2026-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('induccion', 'Inducción'), ('etica', 'Código de ética'), ('gestion', 'Gestión'), ('tecnico', 'Técnico')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('descripcion', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
