# Generated by Django 5.2.12 on 2026-04-09 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documentousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentousuario',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de usuario', 'verbose_name_plural': 'Documentos de usuarios'},
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión'),
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='titulo',
            field=models.CharField(default='Documento sin título', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='archivo',
            field=models.FileField(upload_to='documentos_usuario/%Y/%m/%d/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='documentousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
