# Generated by Django 5.2.12 on 2026-04-13 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documentousuario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLecturaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lectura', models.DateField(blank=True, null=True, verbose_name='Fecha real de lectura')),
                ('fecha_examen', models.DateField(blank=True, null=True, verbose_name='Fecha real del examen')),
                ('nota', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nota (%)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro en sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_creados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lecturas', to='documentos.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lecturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de lectura/examen',
                'verbose_name_plural': 'Historiales de lecturas/exámenes',
                'ordering': ['-fecha_lectura'],
                'unique_together': {('usuario', 'documento')},
            },
        ),
    ]
