# Generated by Django 5.2.12 on 2026-04-20 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_historiallecturaexamen'),
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiallecturaexamen',
            options={'verbose_name': 'Historial de Lectura/Examen', 'verbose_name_plural': 'Historiales de Lectura/Examen'},
        ),
        migrations.RemoveField(
            model_name='historiallecturaexamen',
            name='actualizado_por',
        ),
        migrations.RemoveField(
            model_name='historiallecturaexamen',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='historiallecturaexamen',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='historiallecturaexamen',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='historiallecturaexamen',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='fecha_examen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='fecha_lectura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecepcionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firma_imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('firmado', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='documentos.documento')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_documentos', to='personal.trabajador')),
            ],
            options={
                'ordering': ['-fecha_recepcion'],
                'unique_together': {('trabajador', 'documento')},
            },
        ),
    ]
