# Generated by Django 5.2.12 on 2026-04-20 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_historiallecturaexamen_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiallecturaexamen',
            options={'ordering': ['-fecha_lectura'], 'verbose_name': 'Historial de lectura/examen', 'verbose_name_plural': 'Historiales de lecturas/exámenes'},
        ),
        migrations.RemoveField(
            model_name='historiallecturaexamen',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='historiallecturaexamen',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiallecturaexamen',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiallecturaexamen',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='historiallecturaexamen',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro en sistema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='fecha_examen',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real del examen'),
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='fecha_lectura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real de lectura'),
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nota (%)'),
        ),
        migrations.AlterField(
            model_name='historiallecturaexamen',
            name='observaciones',
            field=models.TextField(blank=True, default=django.utils.timezone.now, verbose_name='Observaciones'),
            preserve_default=False,
        ),
    ]
