# Generated by Django 5.2.12 on 2026-03-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('induccion', 'Inducción'), ('gestion', 'Gestión'), ('tecnico', 'Técnico')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('nota_minima', models.DecimalField(decimal_places=1, default=14.0, max_digits=4)),
                ('max_intentos', models.PositiveIntegerField(default=3)),
                ('tiempo_limite', models.PositiveIntegerField(blank=True, help_text='Minutos', null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intento', models.PositiveIntegerField(default=1)),
                ('puntuacion', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('es_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('puntaje', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
            ],
        ),
    ]
