# Generated by Django 5.2.12 on 2026-03-14 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluaciones', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intento',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='intento',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='personal.trabajador'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.evaluacion'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='evaluaciones.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.intento'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.opcion'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.pregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='intento',
            unique_together={('trabajador', 'evaluacion', 'numero_intento')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaintento',
            unique_together={('intento', 'pregunta')},
        ),
    ]
