# Generated by Django 5.2.12 on 2026-03-23 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
        ('personal', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['nivel', 'titulo']},
        ),
        migrations.AlterModelOptions(
            name='intento',
            options={'ordering': ['evaluacion__nivel', 'fecha_inicio']},
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='cargos_requeridos',
            field=models.ManyToManyField(blank=True, help_text='Cargos que deben rendir esta evaluación. Dejar vacío = aplica a TODOS.', related_name='evaluaciones', to='personal.cargo'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='nivel',
            field=models.CharField(choices=[('induccion', 'Nivel 1 — Inducción General'), ('gestion', 'Nivel 2 — Sistema de Gestión'), ('tecnico_general', 'Nivel 3 — Técnico General'), ('tecnico_especifico', 'Nivel 4 — Técnico Específico')], default='induccion', help_text='Nivel según MAN-02 LABSAF', max_length=30),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tiempo_limite',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos. Dejar vacío = sin límite.', null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='tipo',
            field=models.CharField(choices=[('induccion', 'Inducción'), ('gestion', 'Gestión'), ('tecnico', 'Técnico')], default='induccion', help_text='Tipo para compatibilidad con F-52', max_length=20),
        ),
    ]
