# Generated by Django 5.2.12 on 2026-03-31 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_alter_opcion_options_intento_estado_opcion_orden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={},
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='instrucciones',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='palabras_clave',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuestas_esperadas',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='respuestaintento',
            name='calificada',
        ),
        migrations.RemoveField(
            model_name='respuestaintento',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='respuestaintento',
            name='opciones_seleccionadas',
        ),
        migrations.RemoveField(
            model_name='respuestaintento',
            name='puntaje_obtenido',
        ),
        migrations.RemoveField(
            model_name='respuestaintento',
            name='respuesta_texto',
        ),
        migrations.AlterField(
            model_name='intento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestaintento',
            name='opcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.opcion'),
            preserve_default=False,
        ),
    ]
