# Generated by Django 5.2.12 on 2026-04-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_alter_opcion_options_remove_opcion_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('vf', 'Verdadero/Falso'), ('multiple', 'Opción múltiple')], default='multiple', max_length=10),
        ),
    ]
