# Generated by Django 5.2.12 on 2026-04-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_pregunta_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='opcion',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de aparición'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='instrucciones',
            field=models.TextField(blank=True, help_text='Instrucciones específicas para esta pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='palabras_clave',
            field=models.JSONField(blank=True, default=list, help_text='Palabras clave para evaluar respuesta abierta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuestas_esperadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de respuestas esperadas (para lista, completar)'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='subpreguntas',
            field=models.JSONField(blank=True, default=list, help_text='Para VF en bloque: lista de afirmaciones'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='calificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentario del evaluador'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='opciones_seleccionadas',
            field=models.JSONField(blank=True, default=list, help_text='Para preguntas de múltiple respuesta o VF en bloque'),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='respuestaintento',
            name='respuesta_texto',
            field=models.TextField(blank=True, help_text='Para preguntas abiertas, lista, completar', null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('abierta', 'Pregunta Abierta'), ('vf', 'Verdadero/Falso'), ('vf_bloque', 'VF en bloque'), ('multiple', 'Múltiple Opción (una respuesta)'), ('multiple_respuesta', 'Múltiple Respuesta (varias correctas)'), ('lista', 'Listar Elementos'), ('completar', 'Completar espacios')], default='multiple', help_text='Tipo de pregunta', max_length=20),
        ),
        migrations.AlterField(
            model_name='respuestaintento',
            name='opcion',
            field=models.ForeignKey(blank=True, help_text='Para preguntas de tipo múltiple o VF', null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.opcion'),
        ),
    ]
