# Generated by Django 5.2.12 on 2026-04-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0007_alter_opcion_options_opcion_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('abierta', 'Pregunta Abierta'), ('vf_bloque', 'VF en bloque'), ('multiple', 'Múltiple Opción (una respuesta)'), ('multiple_respuesta', 'Múltiple Respuesta (varias correctas)'), ('lista', 'Listar Elementos'), ('completar', 'Completar espacios')], default='multiple', help_text='Tipo de pregunta', max_length=20),
        ),
    ]
