# Generated by Django 5.2.12 on 2026-03-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0002_initial'),
        ('evaluaciones', '0002_initial'),
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('gestion', 'Sistema de gestión'), ('tecnico', 'Entrenamiento técnico')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('documentos', models.ManyToManyField(blank=True, related_name='modulos', to='documentos.documento')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.evaluacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AvanceEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='personal.trabajador')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='entrenamientos.moduloentrenamiento')),
            ],
            options={
                'unique_together': {('trabajador', 'modulo')},
            },
        ),
    ]
